version: '3.7'

services:
  main:
    container_name: simple_api
    build:
      context: .
      target: build
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5000:5000
      - 9229:9229
    command: npm run start:debug
    networks:
      - webnet

networks:
  webnet:
