name: Build a Docker image and Push it to Docker Hub Container Registry

#This CI Workflow will be executed everytime a commit is pushed (directly or via PR to the selected branches)
on:
  push:
    branches:
      - master
      - develop
#This workflow will be executed also when creating PR's
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - 
        name: 'Checkout from Codebase'
        uses: actions/checkout@v2

      - 
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - 
        name: 'Install nodejs dependencies'
        run: npm ci
  
      - 
        name: 'Run Unit Tests'
        run: npm run test

      - 
        name: 'Dockerhub Registry Login'
        uses: docker/login-action@v1.12.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          username: ${{ secrets.ACR_USERNAME }} # optional
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.ACR_PASSWORD }} # optional
      
      -
        name: 'Build and Push Docker Image'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.ACR_USERNAME }}/cicd:latest

# name: ci

# on:
#   push:
#     branches:
#       - 'main'

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v1
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       -
#         name: Login to DockerHub
#         uses: docker/login-action@v1 
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       -
#         name: Build and push
#         id: docker_build
#         uses: docker/build-push-action@v2
#         with:
#           push: true
#           tags: user/app:latest