name: Build a Docker image and Push it to Docker Hub Container Registry

#This CI Workflow will be executed everytime a commit is pushed (directly or via PR to the selected branches)
on:
  push:
    branches:
      - master
      - develop
#This workflow will be executed also when creating PR'ss
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - 
        name: 'Checkout from Codebase'
        uses: actions/checkout@v2

      - 
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - 
        name: 'Install nodejs dependencies'
        run: npm ci
  
      - 
        name: 'Run Unit Tests'
        run: npm run test
